/* Connection Actions */
export const UPDATE_NETWORK_CONNECTION = 'UPDATE_NETWORK_CONNECTION';

/* Persistent State Actions */
export const RESET_SESSION_STATE = 'RESET_SESSION_STATE';
export const SET_ALL_PERSISTENT = 'SET_ALL_PERSISTENT';
export const UPDATE_APP_STATE = 'UPDATE_APP_STATE';
export const UPDATE_ONE_PERSISTENT = 'UPDATE_ONE_PERSISTENT';
export const SET_SCREEN_DIMS = 'SET_SCREEN_DIMS';

/* Transient State Actions */
export const CLOSE_PROMPT = 'CLOSE_PROMPT';
export const RESET_TRANSIENT_STATE = 'RESET_TRANSIENT_STATE';
export const RESTORE_TRANSIENT_FROM_PERSISTENT = 'RESTORE_TRANSIENT_FROM_PERSISTENT';
export const UPDATE_ONE_TRANSIENT = 'UPDATE_ONE_TRANSIENT';

/* Bluetooth Actions */
export const BEGIN_CONNECT_PERIPHERAL = 'BEGIN_CONNECT_PERIPHERAL';
export const BEGIN_DISCONNECT_PERIPHERAL = 'BEGIN_DISCONNECT_PERIPHERAL';
export const BEGIN_SCAN = 'BEGIN_SCAN';
export const CLEAR_PERIPHERALS = 'CLEAR_PERIPHERALS';
export const CONNECT_PERIPHERAL_FAIL = 'CONNECT_PERIPHERAL_FAIL';
export const CONNECT_PERIPHERAL_SUCCESS = 'CONNECT_PERIPHERAL_SUCCESS';
export const DISABLE_BLUETOOTH_STATE = 'DISABLE_BLUETOOTH_STATE';
export const DISCONNECT_PERIPHERAL_FAIL = 'DISCONNECT_PERIPHERAL_FAIL';
export const DISCONNECT_PERIPHERAL_SUCCESS = 'DISCONNECT_PERIPHERAL_SUCCESS';
export const END_SCAN = 'END_SCAN';
export const SCAN_FOR_ELLIEGRID = 'SCAN_FOR_ELLIEGRID';
export const SET_PERIPHERALS = 'SET_PERIPHERALS';
export const STOP_SCAN = 'STOP_SCAN';
export const UPDATE_BLUETOOTH = 'UPDATE_BLUETOOTH';
export const UPDATE_BLUETOOTH_PERMISSION = 'UPDATE_BLUETOOTH_PERMISSION';
export const UPDATE_BLUETOOTH_STATE = 'UPDATE_BLUETOOTH_STATE';

/* Pill box Actions */
export const BEGIN_INIT_PILLBOX = 'BEGIN_INIT_PILLBOX';
export const DELETE_ALARM_DATA = 'DELETE_ALARM_DATA';
export const INIT_PILLBOX_FAIL = 'INIT_PILLBOX_FAIL';
export const INIT_PILLBOX_SUCCESS = 'INIT_PILLBOX_SUCCESS';
export const SELECT_COMPARTMENT = 'SELECT_COMPARTMENT';
export const SET_PILLBOX_LOADING = 'SET_PILLBOX_LOADING';
export const SET_ALARM_DATA = 'SET_ALARM_DATA';
export const UPDATE_BATTERY_LEVEL = 'UPDATE_BATTERY_LEVEL';
export const UPDATE_DEVICE_INFO = 'UPDATE_DEVICE_INFO';
export const UPDATE_LED_STATE = 'UPDATE_LED_STATE';
export const UPDATE_PILLBOX = 'UPDATE_PILLBOX';
export const UPDATE_PILLBOX_STATE = 'UPDATE_PILLBOX_STATE';
export const UPDATE_VOLUME_LEVEL = 'UPDATE_VOLUME_LEVEL';

/* Firmware Update Actions */
export const RESET_DFU_STATE = 'RESET_DFU_STATE';
export const UPDATE_DFU = 'UPDATE_DFU';
export const UPDATE_DFU_PROGRESS = 'UPDATE_DFU_PROGRESS';

export const RESET_STATE = "RESET_STATE";
